#!/usr/bin/bash

# this is a simple config for herbstluftwm

hc() {
    cmds="$cmds , $@"
}
hc set_layout horizontal
hc emit_hook reload
hc set_monitors 1920x1047+0+33 1920x1047+1920+33
xsetroot -solid '#222222'
picom --shadow-opactiy 0.25 &
# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
myTerminal=rxvt-unicode
Editor=nvim

hc keybind $Mod-Shift-c quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-w close
hc keybind $Ctrl-Shift-t spawn $myTerminal # use your $TERMINAL with xterm as fallback

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-a  focus left
hc keybind $Mod-s  focus down
hc keybind $Mod-w  focus up
hc keybind $Mod-d  focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Left  shift left
hc keybind $Mod-Down  shift down
hc keybind $Mod-Up    shift up
hc keybind $Mod-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-left       resize left +$resizestep
hc keybind $Mod-down      resize down +$resizestep
hc keybind $Mod-up       resize up +$resizestep
hc keybind $Mod-right       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( "Helado", "Dulce", "Pastel", "Azucar", "Chocolate", "Cafe" )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-f floating toggle
hc keybind $Mod-l fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $mod-Shift-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 horizontal vertical max vertical grid    \
               , cycle_layout +1
# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

hc keybind XF86AudioRaiseVolume spawn /home/scouri/audioup.sh
hc keybind XF86AudioLowerVolume spawn /home/scouri/audiodown.sh
# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1


hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 4
hc set focus_follows_mouse 1

hc attr theme.title_height 0
hc attr theme.title_font 'JetBrains Mono:pixelsize=0'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.padding_top 2  # space below the title's baseline (i.e. text depth)
hc attr theme.active.color '#d8dee9'
hc attr theme.normal.color '#5e81ac'
hc attr theme.urgent.color '#5e81ac'
hc attr theme.inner_width 0
hc attr theme.inner_color '#4c566a'
hc attr theme.border_width 3
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color '#000000'
hc attr theme.active.inner_color '#434c5e'
hc attr theme.active.outer_color '#2e3440'
hc attr theme.background_color '#2e3440'

#Floating
hc attr theme.floating.padding_top 20


hc set window_gap 4
hc set frame_padding 4
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
#hc set monitors 1920x1080+0+0 1920x1080+1920+0
hc detect_monitors
hc set tree_style '╾│ ├└╼─┐'

herbstclient chain $cmds &
hc unlock
./lemonbar.sh | lemonbar -n bar -B \#2e3440 -F \#d8dee9 -f 'SF Mono:size=10.8' -f 'JetBrains Mono:style=Italic:size=10.8' -f 'Victor Mono:style=SemiBold Italic:size=10.8' -f 'Noto Sans JP:size=10.8' -f 'mplus Nerd Font:style=Italic:size=10.8' -p -g 1920x30+0+0 | sh &
# unlock, just to be sure


# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

